# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MGCUb-bvC38Bf0SLYoYr4Mmzb8iYHDkg
"""

print('Dupla:Lidyane e Thiago')
print('============================================================================================================================================================')
nome=input ('Digite seu nome:')                                                  # Input é uma função que permite ao usuário inserir informações.
nasc=input ('Digite seu ano de nascimento:')
print('seu ano de nascimento+2022:')                                             # Print mostra a informação entre aspas na tela do usuário. Se não tiver aspas não aparecerá em tela. 
s=int(nasc)+2022                                                                 # s é a soma. Int/inteiro declara que o valor que será inserido é inteiro. (nasc)é uma variável que o usuário irá colocar, como não temos o valor já declarado se faz essêncial o uso do parênteses.                                                          
print(s)
print('=============================================================================================================================================================')
altura=float (input('digite sua altura: '))                                      # Float/Real; declara que o usuário deverá inserir sua altura, os parênteses separam cada função 
if altura >= 1.76:                                                               # If/se; Elife/Se não se; Se a altura do usuário for maior ou igual a 1.76 irá aparecer na tela a função print.
  print('é alta')
elif altura <= 1.75:
  print('é baixinha')
a=int(input ('Digite um número: '))                                              # a e b são váriaveis que serão digitadas pelo usuário.
b=int(input ('Digite outro número:'))
if a!=b:
  print(a+b)
elif a==b:                                                                       # Os dois sinais de igualdade representam comparação.
  print('error')

print('=============================================================================================================================================================')

print("Cálculos:") 
print(a+b)
print(a*b)
print(a/b)

